spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/netcracker
    username: netcracker
    password: netcracker
    driver-class-name: org.postgresql.Driver
    initialization-mode: always
    hikari:
      catalog: jobdealer
      schema: public
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
        jdbc:
          lob:
            non_contextual_creation: true
        ddl-auto: update
    generate-ddl: true
    show-sql: false
    open-in-view: false
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

server:
  port: ${PORT:8080}
  servlet:
    context-path: /api/0.1

logging:
  level:
    org.springframework: INFO
    edu.netcracker.jobdealer: INFO
  pattern:
    console: "%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n"
    file: "%d %p %c{1.} [%t] %m%n"

upload:
  path: "./src/main/resources/default.jpg"